# Generated by Django 5.1.5 on 2025-02-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AddField(
            model_name="transitinformation",
            name="pos_list_coords",
            field=models.TextField(
                blank=True, help_text="Parsed posList as JSON", null=True
            ),
        ),
        migrations.AddField(
            model_name="transitinformation",
            name="pos_list_raw",
            field=models.TextField(
                blank=True, help_text="Raw posList string from XML", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transitinformation",
            name="situation_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
