# Generated by Django 5.1.5 on 2025-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_delete_location_transitinformation_pos_list_coords_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="transitinformation",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
