# Generated by Django 5.1.5 on 2025-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_apimetadata_transitinformation_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitinformation",
            name="area_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
