# Generated by Django 5.1.5 on 2025-02-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_transitinformation_area_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitinformation",
            name="creation_time",
        ),
        migrations.RemoveField(
            model_name="transitinformation",
            name="version_time",
        ),
    ]
