# Generated by Django 5.1.5 on 2025-02-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0006_remove_transitinformation_creation_time_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transitinformation",
            unique_together={("situation_id", "version")},
        ),
    ]
