# Generated by Django 5.1.5 on 2025-02-07 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0007_alter_transitinformation_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transitinformation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="transitinformation",
            name="creation_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="transitinformation",
            name="version_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
