# Generated by Django 5.1.5 on 2025-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0008_alter_transitinformation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitinformation",
            name="filter_used",
            field=models.TextField(blank=True, null=True),
        ),
    ]
