# Generated by Django 5.1.5 on 2025-03-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0010_transitinformation_closure_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitinformation",
            name="closure_reason",
        ),
    ]
