# Generated by Django 5.1.5 on 2025-04-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0011_remove_transitinformation_closure_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitinformation",
            name="closure_type",
        ),
        migrations.RemoveField(
            model_name="transitinformation",
            name="is_road_closed",
        ),
    ]
