# Generated by Django 5.1.4 on 2025-04-02 12:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0012_remove_transitinformation_closure_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitinformation",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="transitinformation",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="transitinformation",
            name="pos_list_coords",
        ),
        migrations.AddField(
            model_name="transitinformation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Primary point location (SRID 4326 WGS84)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="transitinformation",
            name="path",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True,
                help_text="LineString path from posList (SRID 4326 WGS84)",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="transitinformation",
            name="pos_list_raw",
            field=models.TextField(
                blank=True,
                help_text="Raw posList string from XML for reference/debugging",
                null=True,
            ),
        ),
    ]
