# Generated by Django 5.1.4 on 2025-04-08 11:50

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0013_remove_transitinformation_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_ref",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the bus line (e.g., Entur Line ID like 'ATB:Line:1')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Common name of the route (e.g., 'Line 1 Sentrum - Strindheim')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "operator_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Identifier for the operator",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(
                        help_text="Route geometry as a LineString (SRID 4326 WGS84)",
                        srid=4326,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version identifier for this route data (if provided by source)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this route information was last updated in the database",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["line_ref"], name="map_busrout_line_re_afa0fa_idx"
                    ),
                    models.Index(
                        fields=["operator_ref"], name="map_busrout_operato_504fdf_idx"
                    ),
                ],
            },
        ),
    ]
