# Generated by Django 5.1.4 on 2025-04-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0014_busroute"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="busroute",
            name="map_busrout_line_re_afa0fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="busroute",
            name="map_busrout_operato_504fdf_idx",
        ),
        migrations.RemoveField(
            model_name="busroute",
            name="line_ref",
        ),
        migrations.RemoveField(
            model_name="busroute",
            name="name",
        ),
        migrations.RemoveField(
            model_name="busroute",
            name="operator_ref",
        ),
    ]
