# Generated by Django 5.1.4 on 2025-04-08 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0015_remove_busroute_map_busrout_line_re_afa0fa_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="busroute",
            options={"verbose_name": "Bus Route", "verbose_name_plural": "Bus Routes"},
        ),
        migrations.AlterField(
            model_name="busroute",
            name="last_updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this route information was last updated/imported",
            ),
        ),
    ]
