# Generated by Django 5.1.4 on 2025-04-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0016_alter_busroute_options_alter_busroute_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedCollision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transit_lon", models.FloatField()),
                ("transit_lat", models.FloatField()),
                (
                    "detection_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("tolerance_meters", models.IntegerField(default=50)),
                (
                    "bus_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_collisions",
                        to="map.busroute",
                    ),
                ),
                (
                    "transit_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_collisions",
                        to="map.transitinformation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detected Collision",
                "verbose_name_plural": "Detected Collisions",
                "ordering": ["-detection_timestamp", "transit_information"],
                "unique_together": {("transit_information", "bus_route")},
            },
        ),
    ]
