# Generated by Django 5.1.4 on 2025-04-10 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0017_detectedcollision"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detectedcollision",
            options={
                "ordering": ["-detection_timestamp"],
                "verbose_name": "Detected Colliding Transit Point",
                "verbose_name_plural": "Detected Colliding Transit Points",
            },
        ),
        migrations.AlterUniqueTogether(
            name="detectedcollision",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="detectedcollision",
            name="detection_timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="detectedcollision",
            name="transit_information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="detected_collision_record",
                serialize=False,
                to="map.transitinformation",
            ),
        ),
        migrations.RemoveField(
            model_name="detectedcollision",
            name="bus_route",
        ),
        migrations.RemoveField(
            model_name="detectedcollision",
            name="id",
        ),
    ]
